# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [8]:
%run initialise.py

ModuleNotFoundError: No module named 'generators'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
np.version.version

'2.4.3'

#### 3. Create a null vector of size 10 (★☆☆)

In [14]:
null=np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [15]:
null.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [17]:
np.info("add")

     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via t

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [20]:
a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [34]:
a=np.arange(10,50)
print(a)
a=a[-1::-1]
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [38]:
a=np.arange(9)
a=a.reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [40]:
a=np.array([1,2,0,0,4,0])
idx=np.nonzero(a)
print(idx)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [41]:
np.identity(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [43]:
np.random.random([3,3])

array([[0.533546  , 0.62218364, 0.39600077],
       [0.1646606 , 0.72712206, 0.09530397],
       [0.2403836 , 0.590685  , 0.35581776]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [57]:
a=np.random.random([10,10])
print("min = "+str(np.min(a)))
print("max = "+str(np.max(a)))

min = 0.008415836392733134
max = 0.9972369636077767


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [59]:
a=np.random.random(30)
print("mean = "+str(np.mean(a)))

mean = 0.4441734779511046


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [78]:
def make_box(n):
    a=np.zeros([n,n])
    a[[0,-1],:]=1
    a[:,[0,-1]]=1
    return(a)
print(make_box(5))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [127]:
a=np.ones([5,18])
b=np.pad(a,[(1,1),(1,1)])
print(b)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [125]:
# in comments is my answers before running
print(0*np.nan) #nan
print(np.nan == np.nan) #false
print(np.inf > np.nan) #false
print(np.nan - np.nan) # np.nan
print(np.nan in set([np.nan])) #true
print(0.3 == 3 * 0.1) #false
print(float(0.3) == float(3) * 0.1) #false


nan
False
False
nan
True
False
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [131]:
a=np.diag([1,2,3,4])
a=np.pad(a,[(1,0),(0,1)])
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [141]:
a=np.zeros([8,8])
b=np.arange(1,9)+np.arange(1,9).reshape([8,1])
a[b%2==1]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [143]:
first_idx=100//(7*8)
remeinder=100%56
second_idx=remeinder//8
third_idx=remeinder%8
print(first_idx,second_idx,third_idx)

# checking
a=np.arange(0,6*7*8).reshape(6,7,8)
print(a[first_idx,second_idx,third_idx])

1 5 4
100


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [144]:
base_mat=np.array([[1,0],[0,1]])
np.tile(base_mat,[4,4])

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [190]:
a=np.random.random([5,5])
a=a/np.linalg.norm(a)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [191]:
a=np.random.random([5,3])
b=np.random.random([3,2])
c=a@b
print(c)

[[0.76236133 0.6740515 ]
 [0.91681516 0.53639021]
 [0.70689    0.61317688]
 [1.06781318 0.52092614]
 [0.86632659 0.29814021]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [248]:
a=np.random.randint(10,size=10)
b=a[np.bitwise_or(a<3,a>8)]
print(a)
print(b)

[1 6 9 8 3 0 4 2 9 2]
[1 9 0 2 9 2]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [249]:
# my answer 9,9

print(sum(range(5), -1))
from numpy import *

print(sum(range(5), -1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [267]:
# my answer before running in comments
Z= np.arange(5)
print(Z**Z) #legal(if values are greater than 0)
print(2 << Z >> 2) # wtf, guess illeagal
print(Z <- Z) # legal
print(1j*Z) # legal
print(Z/1/1)# legal
print(Z<Z>Z)# illeagal

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [268]:
print(np.array(0) / np.array(0)) # nan
print(np.array(0) // np.array(0)) # 0
print(np.array([np.nan]).astype(int).astype(float) )#0.0

nan
0
[-9.22337204e+18]


C:\Users\USER\AppData\Local\Temp\ipykernel_21492\3253479637.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0)) #nan
C:\Users\USER\AppData\Local\Temp\ipykernel_21492\3253479637.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0)) #nan
C:\Users\USER\AppData\Local\Temp\ipykernel_21492\3253479637.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float) )#0.0


#### 29. How to round away from zero a float array ? (★☆☆)

In [269]:
a=np.random.random(5)*10
print(a)
print(np.ceil(a))

[9.19832639 1.77058787 5.76130394 0.55355386 4.52622973]
[10.  2.  6.  1.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [270]:
a=[1,2,3,4]
b=[3,5,6,7]
print(np.intersect1d(a,b))

[3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
#bp.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [273]:
print(np.sqrt(-1) == np.emath.sqrt(-1)) #false?

False


C:\Users\USER\AppData\Local\Temp\ipykernel_21492\27669877.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1)) #false?


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [278]:
print(np.datetime64("today")-1)
print(np.datetime64("today"))
print(np.datetime64("today")+1)

2026-03-28
2026-03-29
2026-03-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [283]:
a=np.datetime64('2023-06-01')
b=np.datetime64('2023-06-30')
np.arange(a,b)

array(['2023-06-01', '2023-06-02', '2023-06-03', '2023-06-04',
       '2023-06-05', '2023-06-06', '2023-06-07', '2023-06-08',
       '2023-06-09', '2023-06-10', '2023-06-11', '2023-06-12',
       '2023-06-13', '2023-06-14', '2023-06-15', '2023-06-16',
       '2023-06-17', '2023-06-18', '2023-06-19', '2023-06-20',
       '2023-06-21', '2023-06-22', '2023-06-23', '2023-06-24',
       '2023-06-25', '2023-06-26', '2023-06-27', '2023-06-28',
       '2023-06-29'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
A=np.random.random(10)*10
print(a)
print(a//1)
print(a-a%1)
print(np.floor(a))
print(np.ceil(a)-1) ######## does it considered cheating?

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [290]:
a=np.arange(5)
a=np.tile(a,(5,1))
a

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [292]:
np.linspace(0,1,12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [297]:
a=np.random.random(10)
np.sort(a)

array([0.02849277, 0.080918  , 0.18754204, 0.30181861, 0.31719652,
       0.3750018 , 0.60321024, 0.63751781, 0.67448687, 0.89600032])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [301]:
A=np.array([1,2,1,3])
B=np.array([1,2,3])
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [303]:
a=np.array([1,2])
a.flags.writeable=False
a[1]=2

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [379]:
A = np.random.random([10,2])*10-5
rs = np.linalg.norm(A,axis=1)
thetas = np.atan2(A[:,0],A[:,1])
polar = np.vstack([rs,thetas]).T
polar


array([[ 3.55379123, -0.77124446],
       [ 4.30550706,  0.28206291],
       [ 4.42869787,  2.54286263],
       [ 4.28885075, -0.52735692],
       [ 3.81337518,  0.38416936],
       [ 5.29838454, -1.0236368 ],
       [ 2.42948215, -2.8351274 ],
       [ 2.58045272,  0.42163977],
       [ 4.0932267 ,  1.11844454],
       [ 4.30030905,  2.06635322]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [383]:
A=np.random.random(10)
print(A)
A[A==max(A)]=0
print(A)


[0.44968233 0.25067241 0.25560807 0.3905386  0.02697174 0.89624933
 0.08181027 0.69264757 0.14478755 0.94792632]
[0.44968233 0.25067241 0.25560807 0.3905386  0.02697174 0.89624933
 0.08181027 0.69264757 0.14478755 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [416]:
a=np.linspace(0,1,10)[:,np.newaxis]
[x,y]=np.meshgrid(a,a)
np.array([x,y]).transpose()


array([[[0.        , 0.        ],
        [0.        , 0.11111111],
        [0.        , 0.22222222],
        [0.        , 0.33333333],
        [0.        , 0.44444444],
        [0.        , 0.55555556],
        [0.        , 0.66666667],
        [0.        , 0.77777778],
        [0.        , 0.88888889],
        [0.        , 1.        ]],

       [[0.11111111, 0.        ],
        [0.11111111, 0.11111111],
        [0.11111111, 0.22222222],
        [0.11111111, 0.33333333],
        [0.11111111, 0.44444444],
        [0.11111111, 0.55555556],
        [0.11111111, 0.66666667],
        [0.11111111, 0.77777778],
        [0.11111111, 0.88888889],
        [0.11111111, 1.        ]],

       [[0.22222222, 0.        ],
        [0.22222222, 0.11111111],
        [0.22222222, 0.22222222],
        [0.22222222, 0.33333333],
        [0.22222222, 0.44444444],
        [0.22222222, 0.55555556],
        [0.22222222, 0.66666667],
        [0.22222222, 0.77777778],
        [0.22222222, 0.88888889],
        [0

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [406]:
X=np.random.random(10)
Y=np.random.random(10)
C=1/(X-Y)
C

array([ 2.70632031e+00, -5.23226032e+00, -1.04085776e+00,  5.84900600e+00,
       -2.12759634e+02, -3.52129051e+00,  1.12075825e+06, -4.01294923e+00,
       -4.11709384e+00, -1.83072139e+00])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [ ]:
#np.printoptions(threshold=sys.maxsize)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [423]:
A=np.random.random(10)*10
n=3
print(A[np.argmin(np.abs(A-n))])

3.2493213215976646


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [447]:
a=np.random.random([100,2])
x_dif=a[:,0][:,np.newaxis]-a[:,0][np.newaxis,:]
y_dif=a[:,1][:,np.newaxis]-a[:,1][np.newaxis,:]
np.concatenate([x_dif,y_dif])
dists = np.sqrt(x_dif**2+y_dif**2)

array([[0.        , 0.72339276, 0.43733745, 0.65975522, 0.37509582,
        0.7529384 , 0.79560139, 0.94349521, 0.71322345, 0.74278388],
       [0.72339276, 0.        , 0.31983158, 0.62455974, 0.35794272,
        0.47408389, 0.25623831, 0.62122221, 0.03685444, 0.23982127],
       [0.43733745, 0.31983158, 0.        , 0.64101839, 0.07346871,
        0.59394705, 0.36066718, 0.78572026, 0.32370198, 0.44773715],
       [0.65975522, 0.62455974, 0.64101839, 0.        , 0.58965466,
        0.2177566 , 0.86343694, 0.33011997, 0.58895474, 0.42543932],
       [0.37509582, 0.35794272, 0.07346871, 0.58965466, 0.        ,
        0.5645066 , 0.43025322, 0.76049129, 0.35476164, 0.44694741],
       [0.7529384 , 0.47408389, 0.59394705, 0.2177566 , 0.5645066 ,
        0.        , 0.7284962 , 0.19847985, 0.43725661, 0.24225992],
       [0.79560139, 0.25623831, 0.36066718, 0.86343694, 0.43025322,
        0.7284962 , 0.        , 0.87659207, 0.29254189, 0.49598319],
       [0.94349521, 0.62122221, 0.7857202

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [457]:
np.genfromtxt(r'C:\Users\USER\PyCharmMiscProject\54.txt',delimiter=',')

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
for index, value in np.ndenumerate(A):


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [487]:
def gaussian(x,a,mu,sigma):
    return(a*np.exp(-(np.linalg.norm(x-mu,axis=2))/sigma))
a=np.arange(10)
X,Y=np.meshgrid(a,a)
mat=np.concatenate([X[:,:,np.newaxis],Y[:,:,np.newaxis]],axis=2)
gaussian(mat,1,5,2)

array([[0.02914319, 0.04069858, 0.05417824, 0.06770587, 0.07811995,
        0.082085  , 0.07811995, 0.06770587, 0.05417824, 0.04069858],
       [0.04069858, 0.05910575, 0.082085  , 0.10687793, 0.12725621,
        0.13533528, 0.12725621, 0.10687793, 0.082085  , 0.05910575],
       [0.05417824, 0.082085  , 0.11987325, 0.16484071, 0.20574066,
        0.22313016, 0.20574066, 0.16484071, 0.11987325, 0.082085  ],
       [0.06770587, 0.10687793, 0.16484071, 0.24311673, 0.3269219 ,
        0.36787944, 0.3269219 , 0.24311673, 0.16484071, 0.10687793],
       [0.07811995, 0.12725621, 0.20574066, 0.3269219 , 0.49306869,
        0.60653066, 0.49306869, 0.3269219 , 0.20574066, 0.12725621],
       [0.082085  , 0.13533528, 0.22313016, 0.36787944, 0.60653066,
        1.        , 0.60653066, 0.36787944, 0.22313016, 0.13533528],
       [0.07811995, 0.12725621, 0.20574066, 0.3269219 , 0.49306869,
        0.60653066, 0.49306869, 0.3269219 , 0.20574066, 0.12725621],
       [0.06770587, 0.10687793, 0.1648407

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [520]:
a=np.array([1,2,3,8,'a'])
np.random.choice(a,3,replace=True)

array(['8', '3', '2'], dtype='<U21')

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [538]:
a=np.random.random([3,3])

a-=np.mean(a,axis=1)[:,np.newaxis]
a

array([[-0.12597083,  0.0993192 ,  0.02665163],
       [-0.42442434,  0.29516469,  0.12925965],
       [ 0.20327834, -0.30186896,  0.09859062]])

#### 59. How to sort an array by the nth column? (★★☆)

In [558]:
a=np.random.random([4,4])
n=2
idxs=a[:,n].argsort()
a=a[idxs,:]
a

array([[0.31611234, 0.36159341, 0.063355  , 0.92183523],
       [0.00570473, 0.35945092, 0.3698261 , 0.88317274],
       [0.31598506, 0.84159061, 0.57037624, 0.50426624],
       [0.34123533, 0.36857688, 0.88881294, 0.70791313]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [562]:
def have_null_coulmn(mat):
    return(np.any(np.all(mat==0,axis=0),axis=0))

A=np.array([[0,2,3],[0,2,1],[0,0,1]])
have_null_coulmn(A)

np.True_

#### 61. Find the nearest value from a given value in an array (★★☆)

In [591]:
a=np.random.random(10)*10
x=5
print(a)
a[np.argmin(np.abs(a-x))]

[3.515967   6.64188494 4.43460295 6.85301261 3.02075843 0.38823335
 0.03224807 3.35914045 0.35885541 1.18039145]


np.float64(4.4346029537053635)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [604]:
a=np.array([1,2,3,4,5])
idxs=np.array([0,3])
a[idxs]+=1
a

array([2, 2, 3, 5, 5])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [607]:
X=arange(5)+2
I=np.array([1,2,4])
F=X[I]
F

array([3, 4, 6])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [25]:
A=np.random.randint(256,size=[1000,1000,3])
A=A.reshape(-1,3)
B=np.unique(A,axis=0)
B.shape[0]

971104

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [28]:
A=np.random.random([5,5,5,5])
np.sum(A,axis=(2,3))

array([[12.28265674, 13.65625233, 10.0333248 , 13.66154704, 12.32101806],
       [13.21726161, 11.28869799, 10.95873962, 13.84068856, 10.73254189],
       [13.76004673, 13.35538604, 11.86794361, 13.63368833, 14.64903161],
       [10.91492194, 11.38085173, 13.56727729, 14.93289292, 11.28743121],
       [13.90568201, 12.15016179, 10.59391118, 11.92100974, 11.53610802]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [32]:
D=np.random.random(10)
S=np.array([1,4,7])
np.mean(D[S])

np.float64(0.31854458710932204)

#### 69. How to get the diagonal of a dot product? (★★★)

In [33]:
# dot product suppose to return a scalar, no?
a=np.array([1,2,3])
b=np.array([2,3,4])
print(a*b)
print(np.dot(a,b))

[ 2  6 12]
20


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [38]:
a=np.arange(1,6)
idxs= np.arange(np.size(a))*4
b=np.zeros(np.size(a)*4-3)
b[idxs]=a
b


array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [46]:
a=np.random.random([5,5,3])
b=np.random.random([5,5])
elementwise= a*b[:,:,np.newaxis]
print(elementwise)
matrix_mult=np.einsum('ijk,jl->ilk',a,b)
matrix_mult

[[[0.07997052 0.20830159 0.27601358]
  [0.41994442 0.27462617 0.04845208]
  [0.04966086 0.19258967 0.16727484]
  [0.2228009  0.5279386  0.34320028]
  [0.22494649 0.15910812 0.16425546]]

 [[0.38321454 0.19000368 0.28240012]
  [0.32288474 0.16946971 0.4550408 ]
  [0.69794811 0.44731115 0.47636416]
  [0.18128646 0.63667086 0.56582638]
  [0.55661918 0.26688399 0.10803983]]

 [[0.31535624 0.45820379 0.76521745]
  [0.18738363 0.19896652 0.10395909]
  [0.0061034  0.01371364 0.03283105]
  [0.0999602  0.18388574 0.57807309]
  [0.2977479  0.09539505 0.1393332 ]]

 [[0.07561662 0.19393812 0.48457067]
  [0.19146584 0.06281723 0.18174969]
  [0.21528789 0.03649815 0.02164403]
  [0.05370139 0.19832105 0.03874701]
  [0.01947827 0.09305259 0.12844872]]

 [[0.12995321 0.30825808 0.42153294]
  [0.06771966 0.1120292  0.02239061]
  [0.5428344  0.61115972 0.49930958]
  [0.42017148 0.26598275 0.43326647]
  [0.14714511 0.15822328 0.05968814]]]


array([[[1.33214534, 1.87009055, 1.51597355],
        [0.97349861, 1.31086651, 0.91172375],
        [1.60052663, 1.423664  , 1.04385286],
        [1.91498883, 2.35387965, 1.7171931 ],
        [1.58034622, 1.44397124, 1.02554513]],

       [[1.97001022, 1.44594071, 1.59461841],
        [1.25713733, 0.99272688, 1.34031182],
        [1.44029054, 0.89334642, 1.14047316],
        [2.36600662, 1.73067721, 2.17012278],
        [1.64058497, 0.94508435, 1.2794035 ]],

       [[1.08655942, 0.993919  , 1.66266563],
        [0.79395531, 0.93022599, 1.30033689],
        [1.37235274, 1.03071173, 1.17182999],
        [1.56372976, 1.52200119, 2.11681383],
        [1.34501238, 1.07363184, 1.13664735]],

       [[0.94604081, 0.92833121, 1.2297749 ],
        [0.52495967, 0.4891521 , 0.75038692],
        [0.50822595, 0.9349178 , 1.43533654],
        [1.07731935, 1.08173974, 1.55874454],
        [0.74948072, 0.8450853 , 1.32905039]],

       [[1.27920767, 1.45533996, 1.23562818],
        [0.9363246 , 1.164

#### 72. How to swap two rows of an array? (★★★)

In [48]:
A=np.array([[1,2],[3,4]])
A[[0,1]]=A[[1,0]]
A

array([[3, 4],
       [1, 2]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [273]:
triangels = np.random.randint(5,size=[10,3,2])
shifted_triangels=triangels[:,[1,2,0],np.newaxis,:]
line_segments=np.concatenate([triangels[:,:,np.newaxis,:],shifted_triangels],axis=2).reshape([-1,2,2])
# np.argsort(line_segments[:,:,:],axis=(1))
line_segments=np.unique(line_segments,axis=0)
line_segments=np.sort(line_segments,axis=1)
line_segments=np.unique(line_segments,axis=0)

line_segments.shape

(27, 2, 2)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [285]:
C = [5,2,4,0,1]
a = np.arange(5)
A=np.repeat(a,C)
print(C)
np.bincount(A)

[5, 2, 4, 0, 1]


array([5, 2, 4, 0, 1])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [300]:
a=np.arange(10)
window_size=3
b = np.lib.stride_tricks.sliding_window_view(a,window_size)
np.mean(b,axis=1)


array([1., 2., 3., 4., 5., 6., 7., 8.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [301]:
Z=np.arange(10)**2
window_size
np.lib.stride_tricks.sliding_window_view(Z,window_size)

array([[ 0,  1,  4],
       [ 1,  4,  9],
       [ 4,  9, 16],
       [ 9, 16, 25],
       [16, 25, 36],
       [25, 36, 49],
       [36, 49, 64],
       [49, 64, 81]])

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [355]:
P0=np.random.randint(10,size=[5,2])
P1=np.random.randint(10,size=[5,2])
p=np.array([4,7])
p_P0_vec=P0-p[np.newaxis,:]
P0_P1_vec=P0-P1
prep_line=P0_P1_vec[:,[1,0]]*np.array([[1,-1]])
prep_line=prep_line/np.linalg.norm(prep_line,axis=1)[:,np.newaxis]
dist=np.abs(np.sum(prep_line*p_P0_vec,axis=1))
dist

array([1.96116135, 2.86199428, 1.19311752, 0.31622777, 0.72760688])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [365]:
P0=np.random.randint(10,size=[5,2])[:,np.newaxis,:]
P1=np.random.randint(10,size=[5,2])[:,np.newaxis,:]
p=np.random.randint(10,size=[5,2])[np.newaxis,:,:]
p_P0_vec=P0-p
P0_P1_vec=P0-P1
prep_line=P0_P1_vec[:,:,[1,0]]*np.array([[1,-1]])
prep_line=prep_line/np.linalg.norm(prep_line,axis=2)[:,:,np.newaxis]
dist=np.abs(np.sum(prep_line*p_P0_vec,axis=2))
dist

array([[1.21267813, 5.820855  , 4.8507125 , 8.7312825 , 0.72760688],
       [7.07106781, 4.24264069, 3.53553391, 0.70710678, 2.12132034],
       [7.        , 2.        , 6.        , 6.        , 1.        ],
       [5.        , 2.        , 1.        , 3.        , 4.        ],
       [1.41421356, 0.        , 3.53553391, 6.36396103, 2.12132034]])

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [476]:
# fixed_shape=np.array([1,2]).astype('int')
# center=np.array([5,4]).astype('int')
# a=np.arange(100).reshape([10,10])
# def subpart(a,center,fixed_shape):
#     dim=len(fixed_shape)
#     R=np.zeros(fixed_shape*2+1)
#     min_idxs= np.max([np.zeros(dim),center-fixed_shape],axis=0).astype('int')
#     max_idxs=np.min([a.shape,center+fixed_shape],axis=0)
#     R_min_idxs=np.max([fixed_shape-center,np.zeros(dim)],axis=0)
#     R_max_idxs=2*fixed_shape+1+np.min([a.shape-fixed_shape+center,np.zeros(dim)],axis=0)
#     idxs=np.zeros(max_idxs-min_idxs)
#     R_idxs=np.zeros(max_idxs-min_idxs)
#     for i in range(len(fixed_shape)):
#         print(R_min_idxs[i])
#         print(R_max_idxs[i])
#         idxs[:,i]=np.arange(min_idxs[i],max_idxs[i])
#         R_idxs[:,i]=np.arange(R_min_idxs[i],R_max_idxs[i])
#     R[R_idxs]=a[idxs]
#     return(R)
# subpart(a,center,fixed_shape)

0.0
3.0


ValueError: could not broadcast input array from shape (3,) into shape (2,)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [477]:
a=np.arange(1,15)
np.lib.stride_tricks.sliding_window_view(a,4)

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 82. Compute a matrix rank (★★★)

In [478]:
a=np.array([[1,2,3],[1,1,1],[2,3,4]])
np.linalg.matrix_rank(a)

np.int64(2)

#### 83. How to find the most frequent value in an array?

In [489]:
a=np.random.randint(10,size=20)
print(a)
unique_values, counts = np.unique(a, return_counts=True)
unique_values[counts==np.max(counts)]

[7 0 6 9 2 3 2 6 7 3 2 0 1 9 5 2 1 8 4 1]


array([2], dtype=int32)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [527]:
a=np.random.randint(5,size=[10,10])
windows=np.lib.stride_tricks.sliding_window_view(a,[3,3])
continous_windows=windows[np.all(windows,axis=(2,3))]
continous_windows

array([[[4, 3, 3],
        [4, 4, 2],
        [4, 2, 1]],

       [[4, 4, 2],
        [4, 2, 1],
        [1, 3, 4]],

       [[4, 2, 1],
        [1, 3, 4],
        [1, 2, 2]],

       [[2, 1, 1],
        [3, 4, 1],
        [2, 2, 3]],

       [[1, 1, 1],
        [4, 1, 3],
        [2, 3, 3]],

       [[1, 1, 3],
        [1, 3, 4],
        [3, 3, 3]],

       [[1, 3, 4],
        [1, 2, 2],
        [1, 2, 3]],

       [[3, 4, 1],
        [2, 2, 3],
        [2, 3, 3]],

       [[4, 1, 3],
        [2, 3, 3],
        [3, 3, 3]],

       [[1, 3, 4],
        [3, 3, 3],
        [3, 3, 3]],

       [[1, 2, 2],
        [1, 2, 3],
        [2, 1, 4]],

       [[2, 2, 3],
        [2, 3, 3],
        [1, 4, 1]],

       [[2, 3, 3],
        [3, 3, 3],
        [4, 1, 2]],

       [[3, 3, 3],
        [3, 3, 3],
        [1, 2, 1]],

       [[1, 2, 3],
        [2, 1, 4],
        [1, 4, 2]],

       [[2, 3, 3],
        [1, 4, 1],
        [4, 2, 1]],

       [[3, 3, 3],
        [4, 1, 2],
        [2, 1, 3]]

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [533]:
vecs=np.random.random([3,5])
mats=np.random.random([3,3,5])
np.einsum('ijk,jk->i',mats,vecs)

array([4.23618653, 4.82795329, 3.35999144])

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [563]:
a=np.arange(16).reshape(4,4)
b=np.array(np.split(a,2,axis=1))
b=np.array(np.split(b,2,axis=1))
# b=np.split(b,2,axis=2)

np.sum(b,axis=(0,1))


array([[20, 24],
       [36, 40]])

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [601]:
board= np.random.randint(10,size=[10,10])>6
iter_number=10
for i in range(iter_number):
    windows=np.lib.stride_tricks.sliding_window_view(board,[3,3])
    alive_neigbours=np.sum(windows,axis=(2,3))-windows[:,:,1,1]
    alive_neigbours=np.pad(alive_neigbours,1)
    board[alive_neigbours<2]=0
    board[alive_neigbours==3]=1
    board[alive_neigbours>3]=0
    print('_______________________')
    print(board)


_______________________
[[False False False False False False False False False False]
 [False  True  True False False False  True  True False False]
 [False  True  True False False False False  True  True False]
 [False  True False False False False False False False False]
 [False False False False False False False  True False False]
 [False False False  True  True  True False False False False]
 [False False False  True  True False  True  True False False]
 [False False False  True False  True  True  True False False]
 [False False False False  True  True  True False False False]
 [False False False False False False False False False False]]
_______________________
[[False False False False False False False False False False]
 [False  True  True False False False  True  True  True False]
 [False False False False False False  True  True  True False]
 [False  True  True False False False False  True  True False]
 [False False False False  True False False False False False]
 [Fals

#### 89. How to get the n largest values of an array (★★★)

In [608]:
n=5
N=20
a=np.random.random(N)
percentile=100-n/N*100
a[a>np.percentile(a,percentile)]

array([0.77744925, 0.71014981, 0.79443873, 0.68514963, 0.94374862])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

In [616]:
vecs=np.random.random([5,10])# 5 vecs of 10 elements
cartesian_product=np.sum(vecs[:,np.newaxis,:]*vecs[np.newaxis,:,:],axis=2)
cartesian_product

array([[2.64410531, 1.92631573, 2.02445089, 1.72689142, 1.9156414 ],
       [1.92631573, 2.94856341, 2.29179963, 1.90683898, 1.92452668],
       [2.02445089, 2.29179963, 2.67200751, 2.19625146, 2.07168773],
       [1.72689142, 1.90683898, 2.19625146, 2.33202125, 1.91411253],
       [1.9156414 , 1.92452668, 2.07168773, 1.91411253, 2.43574773]])

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [617]:
Z=np.random.random(10000)
print(Z**3)
print(Z*Z*Z)
print(np.pow(Z,3))

[0.00064635 0.16681482 0.44493477 ... 0.33151864 0.00233178 0.02425012]
[0.00064635 0.16681482 0.44493477 ... 0.33151864 0.00233178 0.02425012]
[0.00064635 0.16681482 0.44493477 ... 0.33151864 0.00233178 0.02425012]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [661]:
A=np.random.randint(10,size=[8,3])
B=np.random.randint(10,size=[2,2])
is_contained=A[np.newaxis,np.newaxis,:,:]==B[:,:,np.newaxis,np.newaxis]
is_contained.shape
is_contained=np.any(is_contained,axis=3)
print(is_contained.shape)
is_contained=np.all(is_contained,axis=1)
print(A)
print(B)
is_contained

(2, 2, 8)
[[9 6 3]
 [4 7 9]
 [6 9 0]
 [8 3 0]
 [2 6 0]
 [3 6 5]
 [4 2 5]
 [4 4 3]]
[[2 9]
 [0 9]]


array([[False, False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False, False]])

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [735]:
A=np.random.randint(10,size=[10,3])
unequal_rows=(A[:,:,np.newaxis]-A[:,np.newaxis,:])==0
unequal_rows=np.sum(unequal_rows,axis=(1,2))==3
print(A[unequal_rows,:])


[[5 9 6]
 [0 5 8]
 [7 0 8]
 [0 2 9]
 [1 5 9]
 [6 9 0]
 [5 3 8]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [815]:
a=np.random.randint(20,size=[2])
bits=2**np.arange(6)
b=a[:,np.newaxis]%bits[np.newaxis,:]
b=b[:,:,np.newaxis]//bits[np.newaxis,np.newaxis:]
b=b[:,np.arange(1,6),np.arange(5)]
print(a)
b

[12 10]


array([[0, 0, 1, 1, 0],
       [0, 1, 0, 1, 0]])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [824]:
a=np.random.randint(3,size=[10,3])
print(a)
print(np.unique(a,axis=0))

[[2 0 0]
 [2 1 2]
 [2 0 0]
 [1 2 1]
 [2 0 1]
 [1 0 0]
 [1 1 1]
 [2 1 0]
 [2 0 1]
 [2 2 1]]
[[1 0 0]
 [1 1 1]
 [1 2 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 2]
 [2 2 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [835]:
A=np.arange(5)
B=np.arange(5)+5
inner=np.einsum('i,i->',A,B)
outer=np.einsum('i,j->ij',A,B)
mul=np.einsum('i,i->i',A,B)
outer

array([[ 0,  0,  0,  0,  0],
       [ 5,  6,  7,  8,  9],
       [10, 12, 14, 16, 18],
       [15, 18, 21, 24, 27],
       [20, 24, 28, 32, 36]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [849]:
X=np.array([8,20])
Y=np.array([5,-4])
dists=np.linspace(0,1,30)
path=Y[np.newaxis,:]+dists[:,np.newaxis]*(X[np.newaxis,:]-Y[np.newaxis,:])
path

array([[ 5.        , -4.        ],
       [ 5.10344828, -3.17241379],
       [ 5.20689655, -2.34482759],
       [ 5.31034483, -1.51724138],
       [ 5.4137931 , -0.68965517],
       [ 5.51724138,  0.13793103],
       [ 5.62068966,  0.96551724],
       [ 5.72413793,  1.79310345],
       [ 5.82758621,  2.62068966],
       [ 5.93103448,  3.44827586],
       [ 6.03448276,  4.27586207],
       [ 6.13793103,  5.10344828],
       [ 6.24137931,  5.93103448],
       [ 6.34482759,  6.75862069],
       [ 6.44827586,  7.5862069 ],
       [ 6.55172414,  8.4137931 ],
       [ 6.65517241,  9.24137931],
       [ 6.75862069, 10.06896552],
       [ 6.86206897, 10.89655172],
       [ 6.96551724, 11.72413793],
       [ 7.06896552, 12.55172414],
       [ 7.17241379, 13.37931034],
       [ 7.27586207, 14.20689655],
       [ 7.37931034, 15.03448276],
       [ 7.48275862, 15.86206897],
       [ 7.5862069 , 16.68965517],
       [ 7.68965517, 17.51724138],
       [ 7.79310345, 18.34482759],
       [ 7.89655172,

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [908]:
A = np.random.randint(10,size=[1000,5])/2
n=10
is_int=np.all(A.astype('int')==A,axis=1)
is_multinominal=np.sum(A,axis=1)==10
print(A[np.bitwise_and(is_int,is_multinominal)])

[[2. 0. 0. 4. 4.]
 [3. 3. 1. 0. 3.]
 [2. 4. 0. 1. 3.]
 [3. 0. 2. 2. 3.]
 [2. 1. 0. 4. 3.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [948]:
X=np.random.random(1000)*100
A=np.random.choice(X,size=[500,100000],replace=True)
bootstrapped_means=np.mean(A,axis=0)
print("95%-",np.percentile(bootstrapped_means,95))
print("5%-",np.percentile(bootstrapped_means,5))
print("real mean-",np.mean(X))

95%- 51.657328159475746
5%- 47.53307671724174
real mean- 49.59148732815386
